### ISSUE TITLE
Pdf/Excel Report is Failing and incorrect Spark/html report is generated.

### ISSUE THREAD

**Issue by mkshchdhry** [grasshopper7/extentreports-cucumber7-adapter#26] opened 2023-03-20 14:04 UTC
HI Team,

My Test runner is getting executed and at the end its failed with report generation - 
However, my both feature have scenario. [image1]
![IMG_20230320_140257](https://user-images.githubusercontent.com/43042357/226368276-10f7958c-601f-497d-afcc-322fceb41ccf.jpg)

**Spark/Json/Html report** -
 All scenario/step of executed are coming under first feature only in report. and 2nd feature in report is coming as blank. [image2/image3]
![IMG_20230320_142044](https://user-images.githubusercontent.com/43042357/226368774-c3104647-24d4-41ee-a4d0-03daad395dbf.jpg)

![IMG_20230320_142503](https://user-images.githubusercontent.com/43042357/226369945-385af36a-7f0d-4715-84b0-c23c4b3db2ab.jpg)

**Error for PDF/Excel report**- 
tech.grasshopper.pdf.exception.**PdfReportException**: No scenarios present for feature - Testing - Automation 34567
	at tech.grasshopper.pdf.pojo.cucumber.Feature.checkData(Feature.java:45)
tech.grasshopper.excel.report.exception.**ExcelReportException**: No scenarios present for feature - Testing - Automation 34567
	at tech.grasshopper.extent.data.pojo.Feature.checkData(Feature.java:45)

**Comment by mkshchdhry** [comment] 2023-03-20 14:12
![Uploading IMG_20230320_140505.jpg…]()

**Comment by grasshopper7** [comment] 2023-03-20 16:58
I think you may have hit a bug. Will need to check.

My first impression is that the name of the two Scenario Outlines - "Launch and login to All Required ...." - is the same across two feature files. The adapter code is checking for the first available Scenario Outline and adding the scenarios to it.

This is the reason all the example row scenarios are displayed in the first feature.

Can you try by keeping two different names for the scenario outlines? Check if it works. 

PDF and excel will not be generated for features without any scenarios. This is by design to avoid creating confusing reports.

Thx.

**Comment by mkshchdhry** [comment] 2023-03-20 17:47
Hi,

Firstly, Thanks for prompt response.

I had given different scenario name in 2nd feature file and executed it. ==> its worked with correct info in report.

So, its issue when same Scenario name is being used across diff feature file.
Also, even if Same Scenario name given in Same feature file (i know no-one will give) as well or diff feature file , Report Should not do any merge as Report should be based on how execution was done/how execution flow was

Any idea? Are we planning to fix this? - as Overall reporting should be by Feature, then By Scenario/ScenarioOutline and then by Step

Regards

**Comment by grasshopper7** [comment] 2023-03-20 19:01
This is my current understanding without looking at the adapter code. This will only affect the Feature and Scenario Outline levels.

If you have 2 features having the same name then all the scenario and scenario outlines in the later executed feature will be displayed in the the first feature.

If you have 2 scenario outlines having the same name in a single or multiple feature files, all the example rows will be displayed in the first feature.

This is a very edge case (Not sure the need for same name features or scenario outlines) and to update the code will need significant testing. I will have a look, time permitting, but do not have a time frame or whether this will be fixed.

Thx.

**Comment by grasshopper7** [comment] 2023-04-07 05:04
This is fixed in version 1.12.0

**Closed as completed by grasshopper7** 2023-04-07 05:04 UTC
